from os.path import join
from msk_downsize_pipeline import *
##CONFIG: define your own downsize ratio, the lambda of poisson distribution
DS_MEAN = 6
DS_MEAN_STR = str(DS_MEAN).zfill(3)

##DIRs
RAW_DIR = "../data/"
PROCESSED_DIR= "../data/downsize"
##Count files
BRCA_FULL_CNF = join(RAW_DIR, "counts.ICGC-BRCA-EU_BRCA_22.WGS.SBS-96.tsv") 
OV_FULL_CNF = join(RAW_DIR, "counts.TCGA-OV_OV_mc3.v0.2.8.WXS.SBS-96.tsv")
##OUTPUT files
BRCA_DS_CNF = join(PROCESSED_DIR,'brca-downsize%s_counts.npy'%(DS_MEAN_STR))
BRCA_IDF = join(PROCESSED_DIR, "brca-downsize%s_sample_id.csv"%(DS_MEAN_STR))
OV_DS_CNF=join(PROCESSED_DIR,'ov-downsize%s_counts.npy'%(DS_MEAN_STR))
OV_IDF=join(PROCESSED_DIR,'ov-downsize%s_sample_id.csv'%(DS_MEAN_STR))

rule brca_downsize:
    input:
        BRCA_FULL_CNF
    output:
        BRCA_DS_CNF,
        BRCA_IDF
    run:
        downsize(BRCA_FULL_CNF, BRCA_DS_CNF, BRCA_IDF, DS_MEAN)

rule ov_downsize:
    input:
        OV_FULL_CNF
    output:
        OV_DS_CNF,
        OV_IDF
    run:
        downsize(OV_FULL_CNF, OV_DS_CNF, OV_IDF, DS_MEAN)
